# Simple action to deploy the app on Heroku

name: Heroku CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: AkhileshNS/heroku-deploy@v3.0.0
       with:
        branch: "master"
        heroku_api_key: ${{ secrets.api_key }}
        heroku_email: ${{ secrets.email }}
        heroku_app_name: ${{ secrets.name }}
